kind: pipeline
type: docker
name: java8

steps:
  - name: test
    image: maven:3-eclipse-temurin-8
    commands:
      - mvn -B clean test

---
kind: pipeline
type: docker
name: java11

steps:
  - name: test
    image: maven:3-eclipse-temurin-11
    commands:
      - mvn -B clean test

---
kind: pipeline
type: docker
name: java17

steps:
  - name: test
    image: maven:3-eclipse-temurin-17
    commands:
      - mvn -B clean test
