kind: pipeline
type: docker
name: java11

steps:
  - name: test
    image: eclipse-temurin:11-jdk
    commands:
      - ./mvnw -B clean test

---
kind: pipeline
type: docker
name: java17

steps:
  - name: test
    image: eclipse-temurin:17-jdk
    commands:
      - ./mvnw -B clean test

---
kind: pipeline
type: docker
name: java21

steps:
  - name: test
    image: eclipse-temurin:21-jdk
    commands:
      - ./mvnw -B clean test
